<a href="https://colab.research.google.com/github/Osuni-99/Adaptive-AI-DLP-Research/blob/main/notebooks/05_Public_Dataset_Integration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ==========================================
# Adaptive AI DLP Framework
# Notebook 05
# Public Dataset Integration
# ==========================================

In [2]:
!pip -q install datasets
!pip -q install pandas
!pip -q install numpy
!pip -q install pillow
!pip -q install pyarrow

In [4]:
import os
import json
import pandas as pd
import numpy as np

from datasets import load_dataset

In [5]:
PROJECT_NAME = "Adaptive AI DLP Framework"

print(PROJECT_NAME)

Adaptive AI DLP Framework

In [6]:
folders = [

    "datasets",

    "datasets/custom",

    "datasets/public",

    "datasets/public/enron",

    "datasets/public/funsd",

    "datasets/public/cord",

    "datasets/public/doclaynet",

    "datasets/final"

]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folder Structure Created")

Folder Structure Created

In [7]:
for root, dirs, files in os.walk("datasets"):
    print(root)

datasets
datasets/final
datasets/custom
datasets/public
datasets/public/enron
datasets/public/doclaynet
datasets/public/funsd
datasets/public/cord

In [8]:
dataset_registry = {

    "Custom Dataset":"Classification",

    "Enron":"Email Classification",

    "FUNSD":"Entity Detection",

    "CORD":"Financial Documents",

    "DocLayNet":"Layout Analysis"

}

In [9]:
pd.DataFrame({

    "Dataset":dataset_registry.keys(),

    "Purpose":dataset_registry.values()

})

          Dataset               Purpose
0  Custom Dataset        Classification
1           Enron  Email Classification
2           FUNSD      Entity Detection
3            CORD   Financial Documents
4       DocLayNet       Layout Analysis

In [10]:
class DatasetManager:

    def __init__(self):

        self.datasets={}

    def register(self,name,dataframe,category):

        self.datasets[name]={

            "data":dataframe,

            "category":category

        }

    def summary(self):

        rows=[]

        for name,info in self.datasets.items():

            df=info["data"]

            rows.append({

                "Dataset":name,

                "Category":info["category"],

                "Rows":len(df),

                "Columns":len(df.columns)

            })

        return pd.DataFrame(rows)

In [11]:
manager = DatasetManager()

Enron

In [12]:
print("Loading Enron Dataset...")

Loading Enron Dataset...

In [13]:
enron_dataset = load_dataset("SetFit/enron_spam")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/176 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

train.jsonl:   0%|          | 0.00/101M [00:00<?, ?B/s]

test.jsonl:   0%|          | 0.00/6.27M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [14]:
print(enron_dataset)

DatasetDict({
    train: Dataset({
        features: ['message_id', 'text', 'label', 'label_text', 'subject', 'message', 'date'],
        num_rows: 31716
    })
    test: Dataset({
        features: ['message_id', 'text', 'label', 'label_text', 'subject', 'message', 'date'],
        num_rows: 2000
    })
})

In [15]:
enron_df = enron_dataset["train"].to_pandas()

In [16]:
enron_df.head()

,message_id,text,label,label_text,subject,message,date
0,33214,any software just for 15 $ - 99 $ understandin...,1,spam,any software just for 15 $ - 99 $,understanding oem software\nlead me not into t...,2005-06-18
1,11929,perspective on ferc regulatory action client c...,0,ham,perspective on ferc regulatory action client c...,"19 th , 2 : 00 pm edt\nperspective on ferc reg...",2001-06-19
2,19784,wanted to try ci 4 lis but thought it was way ...,1,spam,wanted to try ci 4 lis but thought it was way ...,viagra at $ 1 . 12 per dose\nready to boost yo...,2004-09-11
3,2209,"enron / hpl actuals for december 11 , 2000 tec...",0,ham,"enron / hpl actuals for december 11 , 2000",teco tap 30 . 000 / enron ; 120 . 000 / hpl ga...,2000-12-12
4,15880,looking for cheap high - quality software ? ro...,1,spam,looking for cheap high - quality software ? ro...,"water past also , burn , course . gave country...",2005-02-13

In [17]:
print(enron_df.columns.tolist())

['message_id', 'text', 'label', 'label_text', 'subject', 'message', 'date']

In [18]:
enron_df = enron_df[
    [
        "message_id",
        "subject",
        "message",
        "label_text"
    ]
]

In [19]:
enron_df = enron_df.rename(columns={

    "message_id":"Document ID",

    "subject":"Subject",

    "message":"Content",

    "label_text":"Original Label"

})

In [20]:
enron_df["Document Type"]="Email"

enron_df["Department"]="Corporate"

enron_df["Industry"]="Enterprise"

enron_df["Format"]="EMAIL"

enron_df["Classification"]="UNKNOWN"

enron_df["Risk"]="UNKNOWN"

enron_df["Sensitive Entities"]="[]"

enron_df["Leakage Score"]=-1

In [21]:
enron_df = enron_df[
    [

        "Document ID",

        "Subject",

        "Content",

        "Document Type",

        "Department",

        "Industry",

        "Classification",

        "Risk",

        "Sensitive Entities",

        "Leakage Score",

        "Format"

    ]
]

In [22]:
manager.register(

    "Enron",

    enron_df,

    "Classification"

)

In [23]:
enron_df.to_csv(

    "datasets/public/enron/enron_standardized.csv",

    index=False

)

In [24]:
manager.summary()

  Dataset        Category   Rows  Columns
0   Enron  Classification  31716       11

FUNSD

In [25]:
print("Loading FUNSD Dataset...")

Loading FUNSD Dataset...

In [26]:
funsd_dataset = load_dataset("nielsr/funsd")

README.md:   0%|          | 0.00/755 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/12.3M [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/4.38M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/149 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/50 [00:00<?, ? examples/s]

In [27]:
print(funsd_dataset)

DatasetDict({
    train: Dataset({
        features: ['id', 'words', 'bboxes', 'ner_tags', 'image'],
        num_rows: 149
    })
    test: Dataset({
        features: ['id', 'words', 'bboxes', 'ner_tags', 'image'],
        num_rows: 50
    })
})

In [28]:
funsd_train = funsd_dataset["train"].to_pandas()

In [29]:
funsd_train.head()

,id,words,bboxes,ner_tags,image
0,0,"[R&D, :, Suggestion:, Date:, Licensee, Yes, No...","[[383, 91, 493, 175], [287, 316, 295, 327], [1...","[0, 3, 3, 3, 5, 3, 3, 0, 1, 2, 2, 2, 2, 2, 3, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...
1,1,"[Brand:, Style:, PHOENIX, Company:, Country:, ...","[[99, 129, 154, 139], [95, 141, 156, 153], [19...","[3, 3, 5, 3, 3, 3, 5, 5, 1, 1, 3, 3, 3, 3, 5, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...
2,2,"[DATE:, INITIATED, BY:, COMPLETION, COUNTRY:, ...","[[80, 207, 127, 221], [80, 235, 169, 249], [17...","[3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 0, 3, 1, 2, 2, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...
3,3,"[SUBJECT:, SAMPLE:, CIGARETTES:, TAR, 9.1, NIC...","[[78, 121, 166, 135], [77, 152, 154, 166], [74...","[3, 3, 3, 3, 5, 3, 5, 3, 5, 3, 5, 3, 3, 5, 5, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...
4,4,"[B&W, WCC, 621800455, Reconstituted, Tobacco, ...","[[286, 71, 342, 89], [488, 366, 539, 380], [90...","[1, 5, 0, 0, 0, 0, 0, 0, 0, 3, 4, 1, 2, 2, 2, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...

In [30]:
print("Rows :", len(funsd_train))
print("Columns :", len(funsd_train.columns))
print(funsd_train.columns.tolist())

Rows : 149
Columns : 5
['id', 'words', 'bboxes', 'ner_tags', 'image']

In [31]:
manager.register(

    "FUNSD",

    funsd_train,

    "Entity Detection"

)

In [32]:
funsd_train.to_csv(

    "datasets/public/funsd/funsd_raw.csv",

    index=False

)

In [33]:
manager.summary()

  Dataset          Category   Rows  Columns
0   Enron    Classification  31716       11
1   FUNSD  Entity Detection    149        5

CORD

In [34]:
print("Loading CORD Sample...")

Loading CORD Sample...

In [35]:
cord_train = load_dataset(

    "naver-clova-ix/cord-v2",

    split="train[:500]"

)

README.md:   0%|          | 0.00/27.0 [00:00<?, ?B/s]

dataset_infos.json:   0%|          | 0.00/1.05k [00:00<?, ?B/s]

data/train-00000-of-00004-b4aaeceff1d90e(…):   0%|          | 0.00/490M [00:00<?, ?B/s]

data/train-00001-of-00004-7dbbe248962764(…):   0%|          | 0.00/441M [00:00<?, ?B/s]

data/train-00002-of-00004-688fe1305a55e5(…):   0%|          | 0.00/444M [00:00<?, ?B/s]

data/train-00003-of-00004-2d0cd200555ed7(…):   0%|          | 0.00/456M [00:00<?, ?B/s]

data/validation-00000-of-00001-cc3c5779f(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/test-00000-of-00001-9c204eb3f4e1179(…):   0%|          | 0.00/234M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/800 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/100 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/100 [00:00<?, ? examples/s]

In [36]:
cord_train = cord_train.to_pandas()

In [37]:
cord_train.head()

,image,ground_truth
0,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": [{""nm"": ""Nasi Campur Bal..."
1,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": [{""nm"": ""SPGTHY BOLOGNAS..."
2,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": [{""nm"": ""HAKAU UDANG"", ""..."
3,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": [{""nm"": ""Bintang Bremer""..."
4,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": {""nm"": ""BASO BIHUN"", ""un..."

In [38]:
print("Rows :", len(cord_train))

print("Columns :", len(cord_train.columns))

print(cord_train.columns.tolist())

Rows : 500
Columns : 2
['image', 'ground_truth']

In [39]:
manager.register(

    "CORD",

    cord_train,

    "Financial Documents"

)

In [40]:
cord_train.to_csv(

    "datasets/public/cord/cord_sample.csv",

    index=False

)

In [41]:
manager.summary()

  Dataset             Category   Rows  Columns
0   Enron       Classification  31716       11
1   FUNSD     Entity Detection    149        5
2    CORD  Financial Documents    500        2

In [42]:
dataset_catalog = pd.DataFrame([

    {

        "Dataset":"Enron",

        "Category":"Classification",

        "Samples":len(enron_df),

        "Status":"Integrated"

    },

    {

        "Dataset":"FUNSD",

        "Category":"Entity Detection",

        "Samples":len(funsd_train),

        "Status":"Integrated"

    },

    {

        "Dataset":"CORD",

        "Category":"Financial Documents",

        "Samples":len(cord_train),

        "Status":"Integrated"

    }

])

dataset_catalog

  Dataset             Category  Samples      Status
0   Enron       Classification    31716  Integrated
1   FUNSD     Entity Detection      149  Integrated
2    CORD  Financial Documents      500  Integrated

In [43]:
dataset_catalog.to_csv(

    "datasets/final/dataset_catalog.csv",

    index=False

)

In [44]:
manager.summary()

  Dataset             Category   Rows  Columns
0   Enron       Classification  31716       11
1   FUNSD     Entity Detection    149        5
2    CORD  Financial Documents    500        2

SROIE

In [49]:
!pip -q install kagglehub

In [50]:
import kagglehub

print("KaggleHub Installed Successfully")

KaggleHub Installed Successfully

In [51]:
path = kagglehub.dataset_download("urbikn/sroie-datasetv2")

print(path)

Downloading to /root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/4.archive...

100%|██████████| 834M/834M [00:09<00:00, 88.2MB/s]

Extracting files...

/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4

In [52]:
import os

dataset_path = "/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4"

print("Dataset Location:")
print(dataset_path)

print("\nFolders:")
for item in os.listdir(dataset_path):
    print(item)

Dataset Location:
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4

Folders:
SROIE2019

In [53]:
for root, dirs, files in os.walk(dataset_path):

    print(root)

    for d in dirs:
        print("📁", d)

    for f in files[:5]:
        print("📄", f)

    print("-"*60)

/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4
📁 SROIE2019
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019
📁 train
📁 test
📁 layoutlm-base-uncased
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019/train
📁 img
📁 box
📁 entities
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019/train/img
📄 X51008123450.jpg
📄 X51006619854.jpg
📄 X51005745214.jpg
📄 X51008142061.jpg
📄 X51007339112.jpg
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019/train/box
📄 X51005605334.txt
📄 X51005301661.txt
📄 X51005745296.txt
📄 X51005685357.txt
📄 X51005442384.txt
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019/train/entities
📄 X51005605334.txt
📄 X51005301661.txt
📄 X51005745296.txt
📄 X51005685357.txt
📄 X51005442384.txt
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019/test
📁 img
📁 box
📁 entities
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019/test/img
📄 X51007339163.jpg
📄 X51006619869.jpg
📄 X51006620182.jpg
📄 X51006557187.jpg
📄 X51005568889.jpg
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019/test/box
📄 X51005433518.txt
📄 X51006311714.txt
📄 X51005361908.txt
📄 X51006557187.txt
📄 X51007103597.txt
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019/test/entities
📄 X51005433518.txt
📄 X51006311714.txt
📄 X51005361908.txt
📄 X51006557187.txt
📄 X51007103597.txt
------------------------------------------------------------
/root/.cache/kagglehub/datasets/urbikn/sroie-datasetv2/versions/4/SROIE2019/layoutlm-base-uncased
📄 tokenizer_config.json
📄 special_tokens_map.json
📄 vocab.txt
📄 config.json
📄 training_args.bin
------------------------------------------------------------

In [ ]:
sroie_path = dataset_path + "/SROIE2019"

train_img = os.path.join(sroie_path, "train", "img")
train_box = os.path.join(sroie_path, "train", "box")
train_entities = os.path.join(sroie_path, "train", "entities")

test_img = os.path.join(sroie_path, "test", "img")
test_box = os.path.join(sroie_path, "test", "box")
test_entities = os.path.join(sroie_path, "test", "entities")

print("Paths configured successfully.")

In [54]:
sroie_path = dataset_path + "/SROIE2019"

train_img = os.path.join(sroie_path, "train", "img")
train_box = os.path.join(sroie_path, "train", "box")
train_entities = os.path.join(sroie_path, "train", "entities")

test_img = os.path.join(sroie_path, "test", "img")
test_box = os.path.join(sroie_path, "test", "box")
test_entities = os.path.join(sroie_path, "test", "entities")

print("Paths configured successfully.")

Paths configured successfully.

In [55]:
print("Training Images :", len(os.listdir(train_img)))
print("Training OCR Files :", len(os.listdir(train_box)))
print("Training Entity Files :", len(os.listdir(train_entities)))

print()

print("Testing Images :", len(os.listdir(test_img)))
print("Testing OCR Files :", len(os.listdir(test_box)))
print("Testing Entity Files :", len(os.listdir(test_entities)))

Training Images : 626
Training OCR Files : 626
Training Entity Files : 626

Testing Images : 347
Testing OCR Files : 347
Testing Entity Files : 347

In [56]:
train_images = sorted(os.listdir(train_img))

sroie_df = pd.DataFrame({
    "Document ID": [f.split(".")[0] for f in train_images],
    "Image File": train_images
})

sroie_df.head()

    Document ID        Image File
0  X00016469612  X00016469612.jpg
1  X00016469619  X00016469619.jpg
2  X00016469620  X00016469620.jpg
3  X00016469622  X00016469622.jpg
4  X00016469623  X00016469623.jpg

In [57]:
sroie_df["Document Type"] = "Receipt"

sroie_df["Department"] = "Finance"

sroie_df["Industry"] = "Retail"

sroie_df["Classification"] = "Pending"

sroie_df["Risk"] = "Pending"

sroie_df["Sensitive Entities"] = "Not Processed"

sroie_df["Leakage Score"] = -1

sroie_df["Format"] = "JPG"

sroie_df.head()

,Document ID,Image File,Document Type,Department,Industry,Classification,Risk,Sensitive Entities,Leakage Score,Format
0,X00016469612,X00016469612.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
1,X00016469619,X00016469619.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
2,X00016469620,X00016469620.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
3,X00016469622,X00016469622.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
4,X00016469623,X00016469623.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG

In [58]:
manager.register(
    "SROIE",
    sroie_df,
    "Financial Entity Extraction"
)

manager.summary()

  Dataset                     Category   Rows  Columns
0   Enron               Classification  31716       11
1   FUNSD             Entity Detection    149        5
2    CORD          Financial Documents    500        2
3   SROIE  Financial Entity Extraction    626       10

In [59]:
os.makedirs("datasets/public/sroie", exist_ok=True)

sroie_df.to_csv(
    "datasets/public/sroie/sroie_standardized.csv",
    index=False
)

print("SROIE dataset saved successfully.")

SROIE dataset saved successfully.

In [60]:
new_row = pd.DataFrame([{
    "Dataset": "SROIE",
    "Category": "Financial Entity Extraction",
    "Samples": len(sroie_df),
    "Status": "Integrated"
}])

dataset_catalog = pd.concat(
    [dataset_catalog, new_row],
    ignore_index=True
)

dataset_catalog

  Dataset                     Category  Samples      Status
0   Enron               Classification    31716  Integrated
1   FUNSD             Entity Detection      149  Integrated
2    CORD          Financial Documents      500  Integrated
3   SROIE  Financial Entity Extraction      626  Integrated

Update Dataset Manifest

In [61]:
dataset_manifest = pd.DataFrame({

    "Dataset":[

        "Custom Dataset",

        "Enron",

        "FUNSD",

        "CORD",

        "SROIE"

    ],

    "Purpose":[

        "SME Document Classification",

        "Email Classification",

        "Named Entity Recognition",

        "Financial Document Understanding",

        "Financial Entity Extraction"

    ],

    "Status":[

        "Completed",

        "Integrated",

        "Integrated",

        "Integrated",

        "Integrated"

    ]

})

dataset_manifest

          Dataset                           Purpose      Status
0  Custom Dataset       SME Document Classification   Completed
1           Enron              Email Classification  Integrated
2           FUNSD          Named Entity Recognition  Integrated
3            CORD  Financial Document Understanding  Integrated
4           SROIE       Financial Entity Extraction  Integrated

In [62]:
dataset_manifest.to_csv(

    "datasets/final/dataset_manifest.csv",

    index=False

)

print("Manifest Saved Successfully")

Manifest Saved Successfully

In [63]:
manager.summary().to_csv(

    "datasets/final/dataset_statistics.csv",

    index=False

)

print("Statistics Saved Successfully")

Statistics Saved Successfully

In [64]:
dataset_catalog.to_csv(

    "datasets/final/dataset_catalog.csv",

    index=False

)

print("Catalog Saved Successfully")

Catalog Saved Successfully

In [65]:
print("="*70)

print("Adaptive AI DLP Dataset Repository")

print("="*70)

print()

print("Datasets Successfully Integrated")

print()

print(manager.summary())

print()

print("Notebook 05 Completed Successfully")

======================================================================
Adaptive AI DLP Dataset Repository
======================================================================

Datasets Successfully Integrated

  Dataset                     Category   Rows  Columns
0   Enron               Classification  31716       11
1   FUNSD             Entity Detection    149        5
2    CORD          Financial Documents    500        2
3   SROIE  Financial Entity Extraction    626       10

Notebook 05 Completed Successfully

In [66]:
print(os.listdir("datasets/final"))

['dataset_manifest.csv', 'dataset_catalog.csv', 'dataset_statistics.csv']

CORD Standardization

In [67]:
print(cord_train.columns.tolist())

['image', 'ground_truth']

In [68]:
cord_standard = pd.DataFrame({
    "Document ID": cord_train.index.astype(str),
    "Document Type": "Receipt",
    "Department": "Finance",
    "Industry": "Retail",
    "Format": "Image + JSON",
    "Classification": "Pending",
    "Risk": "Pending",
    "Sensitive Entities": "Not Processed",
    "Leakage Score": -1
})

cord_standard.head()

,Document ID,Document Type,Department,Industry,Format,Classification,Risk,Sensitive Entities,Leakage Score
0,0,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1
1,1,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1
2,2,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1
3,3,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1
4,4,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1

In [69]:
manager.datasets["CORD"]["data"] = cord_standard

manager.summary()

  Dataset                     Category   Rows  Columns
0   Enron               Classification  31716       11
1   FUNSD             Entity Detection    149        5
2    CORD          Financial Documents    500        9
3   SROIE  Financial Entity Extraction    626       10

In [70]:
os.makedirs("datasets/public/cord", exist_ok=True)

cord_standard.to_csv(
    "datasets/public/cord/cord_standardized.csv",
    index=False
)

print("CORD standardized dataset saved successfully.")

CORD standardized dataset saved successfully.

In [71]:
dataset_catalog.loc[
    dataset_catalog["Dataset"] == "CORD",
    "Samples"
] = len(cord_standard)

dataset_catalog.loc[
    dataset_catalog["Dataset"] == "CORD",
    "Status"
] = "Integrated"

dataset_catalog

  Dataset                     Category  Samples      Status
0   Enron               Classification    31716  Integrated
1   FUNSD             Entity Detection      149  Integrated
2    CORD          Financial Documents      500  Integrated
3   SROIE  Financial Entity Extraction      626  Integrated