<a href="https://colab.research.google.com/github/Osuni-99/Adaptive-AI-DLP-Research/blob/main/notebooks/05_Public_Dataset_Integration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
# ==========================================
# Adaptive AI DLP Framework
# Notebook 05
# Public Dataset Integration
# ==========================================

In [85]:
!pip -q install datasets
!pip -q install pandas
!pip -q install numpy
!pip -q install pillow
!pip -q install pyarrow

In [86]:
import os
import json
import pandas as pd
import numpy as np

from datasets import load_dataset

In [87]:
PROJECT_NAME = "Adaptive AI DLP Framework"

print(PROJECT_NAME)

Adaptive AI DLP Framework

In [88]:
folders = [

    "datasets",

    "datasets/custom",

    "datasets/public",

    "datasets/public/enron",

    "datasets/public/funsd",

    "datasets/public/cord",

    "datasets/public/doclaynet",

    "datasets/final"

]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folder Structure Created")

Folder Structure Created

In [89]:
for root, dirs, files in os.walk("datasets"):
    print(root)

datasets
datasets/final
datasets/custom
datasets/public
datasets/public/sroie
datasets/public/enron
datasets/public/funsd
datasets/public/doclaynet
datasets/public/cord

In [90]:
dataset_registry = {

    "Custom Dataset":"Classification",

    "Enron":"Email Classification",

    "FUNSD":"Entity Detection",

    "CORD":"Financial Documents",

    "DocLayNet":"Layout Analysis"

}

In [91]:
pd.DataFrame({

    "Dataset":dataset_registry.keys(),

    "Purpose":dataset_registry.values()

})

          Dataset               Purpose
0  Custom Dataset        Classification
1           Enron  Email Classification
2           FUNSD      Entity Detection
3            CORD   Financial Documents
4       DocLayNet       Layout Analysis

In [92]:
class DatasetManager:

    def __init__(self):

        self.datasets={}

    def register(self,name,dataframe,category):

        self.datasets[name]={

            "data":dataframe,

            "category":category

        }

    def summary(self):

        rows=[]

        for name,info in self.datasets.items():

            df=info["data"]

            rows.append({

                "Dataset":name,

                "Category":info["category"],

                "Rows":len(df),

                "Columns":len(df.columns)

            })

        return pd.DataFrame(rows)

In [93]:
manager = DatasetManager()

Enron

In [94]:
print("Loading Enron Dataset...")

Loading Enron Dataset...

In [95]:
enron_dataset = load_dataset("SetFit/enron_spam")

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

In [96]:
print(enron_dataset)

DatasetDict({
    train: Dataset({
        features: ['message_id', 'text', 'label', 'label_text', 'subject', 'message', 'date'],
        num_rows: 31716
    })
    test: Dataset({
        features: ['message_id', 'text', 'label', 'label_text', 'subject', 'message', 'date'],
        num_rows: 2000
    })
})

In [97]:
enron_df = enron_dataset["train"].to_pandas()

In [98]:
enron_df.head()

,message_id,text,label,label_text,subject,message,date
0,33214,any software just for 15 $ - 99 $ understandin...,1,spam,any software just for 15 $ - 99 $,understanding oem software\nlead me not into t...,2005-06-18
1,11929,perspective on ferc regulatory action client c...,0,ham,perspective on ferc regulatory action client c...,"19 th , 2 : 00 pm edt\nperspective on ferc reg...",2001-06-19
2,19784,wanted to try ci 4 lis but thought it was way ...,1,spam,wanted to try ci 4 lis but thought it was way ...,viagra at $ 1 . 12 per dose\nready to boost yo...,2004-09-11
3,2209,"enron / hpl actuals for december 11 , 2000 tec...",0,ham,"enron / hpl actuals for december 11 , 2000",teco tap 30 . 000 / enron ; 120 . 000 / hpl ga...,2000-12-12
4,15880,looking for cheap high - quality software ? ro...,1,spam,looking for cheap high - quality software ? ro...,"water past also , burn , course . gave country...",2005-02-13

In [99]:
print(enron_df.columns.tolist())

['message_id', 'text', 'label', 'label_text', 'subject', 'message', 'date']

In [100]:
enron_df = enron_df[
    [
        "message_id",
        "subject",
        "message",
        "label_text"
    ]
]

In [101]:
enron_df = enron_df.rename(columns={

    "message_id":"Document ID",

    "subject":"Subject",

    "message":"Content",

    "label_text":"Original Label"

})

In [102]:
enron_df["Document Type"]="Email"

enron_df["Department"]="Corporate"

enron_df["Industry"]="Enterprise"

enron_df["Format"]="EMAIL"

enron_df["Classification"]="UNKNOWN"

enron_df["Risk"]="UNKNOWN"

enron_df["Sensitive Entities"]="[]"

enron_df["Leakage Score"]=-1

In [103]:
enron_df = enron_df[
    [

        "Document ID",

        "Subject",

        "Content",

        "Document Type",

        "Department",

        "Industry",

        "Classification",

        "Risk",

        "Sensitive Entities",

        "Leakage Score",

        "Format"

    ]
]

In [104]:
manager.register(

    "Enron",

    enron_df,

    "Classification"

)

In [105]:
enron_df.to_csv(

    "datasets/public/enron/enron_standardized.csv",

    index=False

)

In [106]:
manager.summary()

  Dataset        Category   Rows  Columns
0   Enron  Classification  31716       11

FUNSD

In [107]:
print("Loading FUNSD Dataset...")

Loading FUNSD Dataset...

In [108]:
funsd_dataset = load_dataset("nielsr/funsd")

In [109]:
print(funsd_dataset)

DatasetDict({
    train: Dataset({
        features: ['id', 'words', 'bboxes', 'ner_tags', 'image'],
        num_rows: 149
    })
    test: Dataset({
        features: ['id', 'words', 'bboxes', 'ner_tags', 'image'],
        num_rows: 50
    })
})

In [110]:
funsd_train = funsd_dataset["train"].to_pandas()

In [111]:
funsd_train.head()

,id,words,bboxes,ner_tags,image
0,0,"[R&D, :, Suggestion:, Date:, Licensee, Yes, No...","[[383, 91, 493, 175], [287, 316, 295, 327], [1...","[0, 3, 3, 3, 5, 3, 3, 0, 1, 2, 2, 2, 2, 2, 3, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...
1,1,"[Brand:, Style:, PHOENIX, Company:, Country:, ...","[[99, 129, 154, 139], [95, 141, 156, 153], [19...","[3, 3, 5, 3, 3, 3, 5, 5, 1, 1, 3, 3, 3, 3, 5, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...
2,2,"[DATE:, INITIATED, BY:, COMPLETION, COUNTRY:, ...","[[80, 207, 127, 221], [80, 235, 169, 249], [17...","[3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 0, 3, 1, 2, 2, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...
3,3,"[SUBJECT:, SAMPLE:, CIGARETTES:, TAR, 9.1, NIC...","[[78, 121, 166, 135], [77, 152, 154, 166], [74...","[3, 3, 3, 3, 5, 3, 5, 3, 5, 3, 5, 3, 3, 5, 5, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...
4,4,"[B&W, WCC, 621800455, Reconstituted, Tobacco, ...","[[286, 71, 342, 89], [488, 366, 539, 380], [90...","[1, 5, 0, 0, 0, 0, 0, 0, 0, 3, 4, 1, 2, 2, 2, ...",{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...

In [112]:
print("Rows :", len(funsd_train))
print("Columns :", len(funsd_train.columns))
print(funsd_train.columns.tolist())

Rows : 149
Columns : 5
['id', 'words', 'bboxes', 'ner_tags', 'image']

In [113]:
manager.register(

    "FUNSD",

    funsd_train,

    "Entity Detection"

)

In [114]:
funsd_train.to_csv(

    "datasets/public/funsd/funsd_raw.csv",

    index=False

)

In [115]:
manager.summary()

  Dataset          Category   Rows  Columns
0   Enron    Classification  31716       11
1   FUNSD  Entity Detection    149        5

CORD

In [116]:
print("Loading CORD Sample...")

Loading CORD Sample...

In [117]:
cord_train = load_dataset(

    "naver-clova-ix/cord-v2",

    split="train[:500]"

)

In [118]:
cord_train = cord_train.to_pandas()

In [119]:
cord_train.head()

,image,ground_truth
0,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": [{""nm"": ""Nasi Campur Bal..."
1,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": [{""nm"": ""SPGTHY BOLOGNAS..."
2,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": [{""nm"": ""HAKAU UDANG"", ""..."
3,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": [{""nm"": ""Bintang Bremer""..."
4,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"{""gt_parse"": {""menu"": {""nm"": ""BASO BIHUN"", ""un..."

In [120]:
print("Rows :", len(cord_train))

print("Columns :", len(cord_train.columns))

print(cord_train.columns.tolist())

Rows : 500
Columns : 2
['image', 'ground_truth']

In [121]:
manager.register(

    "CORD",

    cord_train,

    "Financial Documents"

)

In [122]:
cord_train.to_csv(

    "datasets/public/cord/cord_sample.csv",

    index=False

)

In [123]:
manager.summary()

  Dataset             Category   Rows  Columns
0   Enron       Classification  31716       11
1   FUNSD     Entity Detection    149        5
2    CORD  Financial Documents    500        2

In [124]:
dataset_catalog = pd.DataFrame([

    {

        "Dataset":"Enron",

        "Category":"Classification",

        "Samples":len(enron_df),

        "Status":"Integrated"

    },

    {

        "Dataset":"FUNSD",

        "Category":"Entity Detection",

        "Samples":len(funsd_train),

        "Status":"Integrated"

    },

    {

        "Dataset":"CORD",

        "Category":"Financial Documents",

        "Samples":len(cord_train),

        "Status":"Integrated"

    }

])

dataset_catalog

  Dataset             Category  Samples      Status
0   Enron       Classification    31716  Integrated
1   FUNSD     Entity Detection      149  Integrated
2    CORD  Financial Documents      500  Integrated

In [125]:
dataset_catalog.to_csv(

    "datasets/final/dataset_catalog.csv",

    index=False

)

In [126]:
manager.summary()

  Dataset             Category   Rows  Columns
0   Enron       Classification  31716       11
1   FUNSD     Entity Detection    149        5
2    CORD  Financial Documents    500        2

SROIE

In [127]:
!pip -q install kagglehub

In [128]:
import kagglehub

print("KaggleHub Installed Successfully")

KaggleHub Installed Successfully

In [129]:
path = kagglehub.dataset_download("urbikn/sroie-datasetv2")

print(path)

Using Colab cache for faster access to the 'sroie-datasetv2' dataset.
/kaggle/input/sroie-datasetv2

In [130]:

!pip install -q kagglehub

import os
import kagglehub

# Download or locate the dataset using KaggleHub
dataset_path = kagglehub.dataset_download("urbikn/sroie-datasetv2")

print("Dataset Location:")
print(dataset_path)

print("\nFolders and files:")
for item in os.listdir(dataset_path):
    print(item)

Using Colab cache for faster access to the 'sroie-datasetv2' dataset.
Dataset Location:
/kaggle/input/sroie-datasetv2

Folders and files:
SROIE2019

In [131]:
for root, dirs, files in os.walk(dataset_path):

    print(root)

    for d in dirs:
        print("📁", d)

    for f in files[:5]:
        print("📄", f)

    print("-"*60)

/kaggle/input/sroie-datasetv2
📁 SROIE2019
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019
📁 layoutlm-base-uncased
📁 test
📁 train
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019/layoutlm-base-uncased
📄 config.json
📄 training_args.bin
📄 tokenizer_config.json
📄 pytorch_model.bin
📄 special_tokens_map.json
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019/test
📁 box
📁 entities
📁 img
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019/test/box
📄 X51006008082.txt
📄 X51008099090.txt
📄 X51005806692.txt
📄 X51006733495.txt
📄 X51007846387.txt
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019/test/entities
📄 X51006008082.txt
📄 X51008099090.txt
📄 X51005806692.txt
📄 X51006733495.txt
📄 X51007846387.txt
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019/test/img
📄 X51005719889.jpg
📄 X51005447859.jpg
📄 X51006619863.jpg
📄 X51006619784.jpg
📄 X51006733495.jpg
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019/train
📁 box
📁 entities
📁 img
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019/train/box
📄 X51005705760.txt
📄 X51005361950.txt
📄 X51007339152.txt
📄 X51006557164.txt
📄 X51008164999.txt
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019/train/entities
📄 X51005705760.txt
📄 X51005361950.txt
📄 X51007339152.txt
📄 X51006557164.txt
📄 X51008164999.txt
------------------------------------------------------------
/kaggle/input/sroie-datasetv2/SROIE2019/train/img
📄 X51007231344.jpg
📄 X51005442344.jpg
📄 X51008142030.jpg
📄 X51005447853.jpg
📄 X51007339113.jpg
------------------------------------------------------------

In [132]:
sroie_path = dataset_path + "/SROIE2019"

train_img = os.path.join(sroie_path, "train", "img")
train_box = os.path.join(sroie_path, "train", "box")
train_entities = os.path.join(sroie_path, "train", "entities")

test_img = os.path.join(sroie_path, "test", "img")
test_box = os.path.join(sroie_path, "test", "box")
test_entities = os.path.join(sroie_path, "test", "entities")

print("Paths configured successfully.")

Paths configured successfully.

In [133]:
sroie_path = dataset_path + "/SROIE2019"

train_img = os.path.join(sroie_path, "train", "img")
train_box = os.path.join(sroie_path, "train", "box")
train_entities = os.path.join(sroie_path, "train", "entities")

test_img = os.path.join(sroie_path, "test", "img")
test_box = os.path.join(sroie_path, "test", "box")
test_entities = os.path.join(sroie_path, "test", "entities")

print("Paths configured successfully.")

Paths configured successfully.

In [134]:
print("Training Images :", len(os.listdir(train_img)))
print("Training OCR Files :", len(os.listdir(train_box)))
print("Training Entity Files :", len(os.listdir(train_entities)))

print()

print("Testing Images :", len(os.listdir(test_img)))
print("Testing OCR Files :", len(os.listdir(test_box)))
print("Testing Entity Files :", len(os.listdir(test_entities)))

Training Images : 626
Training OCR Files : 626
Training Entity Files : 626

Testing Images : 347
Testing OCR Files : 347
Testing Entity Files : 347

In [135]:
train_images = sorted(os.listdir(train_img))

sroie_df = pd.DataFrame({
    "Document ID": [f.split(".")[0] for f in train_images],
    "Image File": train_images
})

sroie_df.head()

    Document ID        Image File
0  X00016469612  X00016469612.jpg
1  X00016469619  X00016469619.jpg
2  X00016469620  X00016469620.jpg
3  X00016469622  X00016469622.jpg
4  X00016469623  X00016469623.jpg

In [136]:
sroie_df["Document Type"] = "Receipt"

sroie_df["Department"] = "Finance"

sroie_df["Industry"] = "Retail"

sroie_df["Classification"] = "Pending"

sroie_df["Risk"] = "Pending"

sroie_df["Sensitive Entities"] = "Not Processed"

sroie_df["Leakage Score"] = -1

sroie_df["Format"] = "JPG"

sroie_df.head()

,Document ID,Image File,Document Type,Department,Industry,Classification,Risk,Sensitive Entities,Leakage Score,Format
0,X00016469612,X00016469612.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
1,X00016469619,X00016469619.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
2,X00016469620,X00016469620.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
3,X00016469622,X00016469622.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
4,X00016469623,X00016469623.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG

In [137]:
manager.register(
    "SROIE",
    sroie_df,
    "Financial Entity Extraction"
)

manager.summary()

  Dataset                     Category   Rows  Columns
0   Enron               Classification  31716       11
1   FUNSD             Entity Detection    149        5
2    CORD          Financial Documents    500        2
3   SROIE  Financial Entity Extraction    626       10

In [138]:
os.makedirs("datasets/public/sroie", exist_ok=True)

sroie_df.to_csv(
    "datasets/public/sroie/sroie_standardized.csv",
    index=False
)

print("SROIE dataset saved successfully.")

SROIE dataset saved successfully.

In [139]:
new_row = pd.DataFrame([{
    "Dataset": "SROIE",
    "Category": "Financial Entity Extraction",
    "Samples": len(sroie_df),
    "Status": "Integrated"
}])

dataset_catalog = pd.concat(
    [dataset_catalog, new_row],
    ignore_index=True
)

dataset_catalog

  Dataset                     Category  Samples      Status
0   Enron               Classification    31716  Integrated
1   FUNSD             Entity Detection      149  Integrated
2    CORD          Financial Documents      500  Integrated
3   SROIE  Financial Entity Extraction      626  Integrated

Update Dataset Manifest

In [140]:
dataset_manifest = pd.DataFrame({

    "Dataset":[

        "Custom Dataset",

        "Enron",

        "FUNSD",

        "CORD",

        "SROIE"

    ],

    "Purpose":[

        "SME Document Classification",

        "Email Classification",

        "Named Entity Recognition",

        "Financial Document Understanding",

        "Financial Entity Extraction"

    ],

    "Status":[

        "Completed",

        "Integrated",

        "Integrated",

        "Integrated",

        "Integrated"

    ]

})

dataset_manifest

          Dataset                           Purpose      Status
0  Custom Dataset       SME Document Classification   Completed
1           Enron              Email Classification  Integrated
2           FUNSD          Named Entity Recognition  Integrated
3            CORD  Financial Document Understanding  Integrated
4           SROIE       Financial Entity Extraction  Integrated

In [141]:
dataset_manifest.to_csv(

    "datasets/final/dataset_manifest.csv",

    index=False

)

print("Manifest Saved Successfully")

Manifest Saved Successfully

In [142]:
manager.summary().to_csv(

    "datasets/final/dataset_statistics.csv",

    index=False

)

print("Statistics Saved Successfully")

Statistics Saved Successfully

In [143]:
dataset_catalog.to_csv(

    "datasets/final/dataset_catalog.csv",

    index=False

)

print("Catalog Saved Successfully")

Catalog Saved Successfully

In [144]:
print("="*70)

print("Adaptive AI DLP Dataset Repository")

print("="*70)

print()

print("Datasets Successfully Integrated")

print()

print(manager.summary())

print()

print("Notebook 05 Completed Successfully")

======================================================================
Adaptive AI DLP Dataset Repository
======================================================================

Datasets Successfully Integrated

  Dataset                     Category   Rows  Columns
0   Enron               Classification  31716       11
1   FUNSD             Entity Detection    149        5
2    CORD          Financial Documents    500        2
3   SROIE  Financial Entity Extraction    626       10

Notebook 05 Completed Successfully

In [145]:
print(os.listdir("datasets/final"))

['dataset_statistics.csv', 'dataset_catalog.csv', 'dataset_manifest.csv']

CORD Standardization

In [146]:
print(cord_train.columns.tolist())

['image', 'ground_truth']

In [147]:
cord_standard = pd.DataFrame({
    "Document ID": cord_train.index.astype(str),
    "Document Type": "Receipt",
    "Department": "Finance",
    "Industry": "Retail",
    "Format": "Image + JSON",
    "Classification": "Pending",
    "Risk": "Pending",
    "Sensitive Entities": "Not Processed",
    "Leakage Score": -1
})

cord_standard.head()

,Document ID,Document Type,Department,Industry,Format,Classification,Risk,Sensitive Entities,Leakage Score
0,0,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1
1,1,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1
2,2,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1
3,3,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1
4,4,Receipt,Finance,Retail,Image + JSON,Pending,Pending,Not Processed,-1

In [148]:
manager.datasets["CORD"]["data"] = cord_standard

manager.summary()

  Dataset                     Category   Rows  Columns
0   Enron               Classification  31716       11
1   FUNSD             Entity Detection    149        5
2    CORD          Financial Documents    500        9
3   SROIE  Financial Entity Extraction    626       10

In [149]:
os.makedirs("datasets/public/cord", exist_ok=True)

cord_standard.to_csv(
    "datasets/public/cord/cord_standardized.csv",
    index=False
)

print("CORD standardized dataset saved successfully.")

CORD standardized dataset saved successfully.

In [150]:
dataset_catalog.loc[
    dataset_catalog["Dataset"] == "CORD",
    "Samples"
] = len(cord_standard)

dataset_catalog.loc[
    dataset_catalog["Dataset"] == "CORD",
    "Status"
] = "Integrated"

dataset_catalog

  Dataset                     Category  Samples      Status
0   Enron               Classification    31716  Integrated
1   FUNSD             Entity Detection      149  Integrated
2    CORD          Financial Documents      500  Integrated
3   SROIE  Financial Entity Extraction      626  Integrated

In [151]:

import pandas as pd

dataset_catalog = pd.DataFrame([
    {
        "Dataset": "Enron",
        "Category": "Classification",
        "Samples": 31716,
        "Status": "Integrated"
    },
    {
        "Dataset": "FUNSD",
        "Category": "Entity Detection",
        "Samples": 149,
        "Status": "Integrated"
    },
    {
        "Dataset": "CORD",
        "Category": "Financial Documents",
        "Samples": 500,
        "Status": "Integrated"
    },
    {
        "Dataset": "SROIE",
        "Category": "Financial Entity Extraction",
        "Samples": 626,
        "Status": "Integrated"
    }
])

print(dataset_catalog.to_string(index=False))
print("\nTotal datasets:", len(dataset_catalog))
print("Total registered samples:", dataset_catalog["Samples"].sum())

Dataset                    Category  Samples     Status
  Enron              Classification    31716 Integrated
  FUNSD            Entity Detection      149 Integrated
   CORD         Financial Documents      500 Integrated
  SROIE Financial Entity Extraction      626 Integrated

Total datasets: 4
Total registered samples: 32991

In [152]:
dataset_names = ["enron", "funsd", "cord_standard", "sroie"]

for name in dataset_names:
    if name in globals():
        obj = globals()[name]
        print(f"{name}: Available | Type: {type(obj).__name__}")

        if hasattr(obj, "shape"):
            print("  Shape:", obj.shape)
    else:
        print(f"{name}: Not found in current runtime")

enron: Not found in current runtime
funsd: Not found in current runtime
cord_standard: Available | Type: DataFrame
  Shape: (500, 9)
sroie: Not found in current runtime

In [153]:
for name in sorted(globals()):
    if any(key in name.lower() for key in [
        "enron", "funsd", "cord", "sroie", "dataset"
    ]):
        obj = globals()[name]
        if hasattr(obj, "shape"):
            print(name, "->", obj.shape)
        else:
            print(name, "->", type(obj).__name__)

DatasetManager -> type
cord_standard -> (500, 9)
cord_train -> (500, 2)
dataset_catalog -> (4, 4)
dataset_manifest -> (5, 3)
dataset_names -> list
dataset_path -> str
dataset_registry -> dict
enron_dataset -> {'train': (31716, 7), 'test': (2000, 7)}
enron_df -> (31716, 11)
funsd_dataset -> {'train': (149, 5), 'test': (50, 5)}
funsd_train -> (149, 5)
load_dataset -> function
sroie_df -> (626, 10)
sroie_path -> str

In [154]:
print("Enron dataset loaded:", "enron_dataset" in globals())

print("\nDataset splits:")
print(enron_dataset)

print("\nTraining records:", len(enron_dataset["train"]))
print("Testing records:", len(enron_dataset["test"]))

Enron dataset loaded: True

Dataset splits:
DatasetDict({
    train: Dataset({
        features: ['message_id', 'text', 'label', 'label_text', 'subject', 'message', 'date'],
        num_rows: 31716
    })
    test: Dataset({
        features: ['message_id', 'text', 'label', 'label_text', 'subject', 'message', 'date'],
        num_rows: 2000
    })
})

Training records: 31716
Testing records: 2000

In [155]:
print("FUNSD variables:")

for name in globals():
    if "funsd" in name.lower():
        obj = globals()[name]
        print(name, type(obj).__name__)

        if hasattr(obj, "shape"):
            print("Shape:", obj.shape)

        elif hasattr(obj, "num_rows"):
            print("Rows:", obj.num_rows)

FUNSD variables:
funsd_dataset DatasetDict
Shape: {'train': (149, 5), 'test': (50, 5)}
funsd_train DataFrame
Shape: (149, 5)

In [156]:
print("SROIE-related variables:")

for name in sorted(globals()):
    if "sroie" in name.lower():
        obj = globals()[name]
        print(name, type(obj).__name__)

        if hasattr(obj, "shape"):
            print("Shape:", obj.shape)
        elif hasattr(obj, "num_rows"):
            print("Rows:", obj.num_rows)

SROIE-related variables:
sroie_df DataFrame
Shape: (626, 10)
sroie_path str

Final validation

In [157]:

print("SROIE DataFrame validation")
print("-" * 35)

print("Shape:", sroie_df.shape)
print("\nColumns:")
print(sroie_df.columns.tolist())

print("\nMissing values:")
print(sroie_df.isnull().sum())

print("\nFirst 3 rows:")
display(sroie_df.head(3))

SROIE DataFrame validation
-----------------------------------
Shape: (626, 10)

Columns:
['Document ID', 'Image File', 'Document Type', 'Department', 'Industry', 'Classification', 'Risk', 'Sensitive Entities', 'Leakage Score', 'Format']

Missing values:
Document ID           0
Image File            0
Document Type         0
Department            0
Industry              0
Classification        0
Risk                  0
Sensitive Entities    0
Leakage Score         0
Format                0
dtype: int64

First 3 rows:

,Document ID,Image File,Document Type,Department,Industry,Classification,Risk,Sensitive Entities,Leakage Score,Format
0,X00016469612,X00016469612.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
1,X00016469619,X00016469619.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG
2,X00016469620,X00016469620.jpg,Receipt,Finance,Retail,Pending,Pending,Not Processed,-1,JPG

In [158]:
print("SROIE rows:", len(sroie_df))
print("Columns:", len(sroie_df.columns))
print("\nMissing values:")
print(sroie_df.isnull().sum())
print("\nDocument types:")
print(sroie_df["Document Type"].value_counts())
print("\nFormats:")
print(sroie_df["Format"].value_counts())

SROIE rows: 626
Columns: 10

Missing values:
Document ID           0
Image File            0
Document Type         0
Department            0
Industry              0
Classification        0
Risk                  0
Sensitive Entities    0
Leakage Score         0
Format                0
dtype: int64

Document types:
Document Type
Receipt    626
Name: count, dtype: int64

Formats:
Format
JPG    626
Name: count, dtype: int64

In [159]:
print("FINAL DATASET STATUS")
print("=" * 40)

print("Enron train:", len(enron_dataset["train"]))
print("Enron test:", len(enron_dataset["test"]))

print("FUNSD train:", len(funsd_dataset["train"]))
print("FUNSD test:", len(funsd_dataset["test"]))

print("CORD:", cord_standard.shape)
print("SROIE:", sroie_df.shape)

print("\nSROIE missing values:",
      int(sroie_df.isnull().sum().sum()))

FINAL DATASET STATUS
========================================
Enron train: 31716
Enron test: 2000
FUNSD train: 149
FUNSD test: 50
CORD: (500, 9)
SROIE: (626, 10)

SROIE missing values: 0